Estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title=' API`s Estoque DSC ')

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('gerenciador.urls')),
    path('', include('estoques.urls')),
    path('', include('produtos.urls')),
    path('', include('vendas.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger/', schema_view),

]

gerenciador/urls.py
from django.urls import path

from gerenciador.views import IndexView, GeneratePDFVendas

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('vendas-chart/', IndexView.vendas_chart, name='vendas-chart'),
    path('estoques-chart/', IndexView.estoques_chart, name='estoques-chart'),
    path('relatorio/', GeneratePDFVendas.as_view(), name='relatorio'),
]

vendas/urls.py
from django.urls import path, include
from .views import VendasView, VendasListView, VendasDeleteView, VendasUpdateView

from rest_framework import routers
from .api.viewsets import VendaViewSet

router = routers.DefaultRouter()
router.register(r'venda', VendaViewSet)

urlpatterns = [
    path('api', include(router.urls)),
    path('venda/<int:pk>', VendasView.as_view(), name="venda"),
    path('listarVenda/', VendasListView.as_view(), name='venda_list'),
    path('editarVenda/<int:pk>', VendasUpdateView.as_view(), name='venda_update'),
    path('deletarVenda/<int:pk>/', VendasDeleteView.as_view(), name='venda_delete'),
]

estoques/models.py
from django.db import models

class Estoque(models.Model):
    nome = models.CharField(max_length=100)
    usuario = models.ForeignKey("accounts.CustomUsuario", db_column='id_usuario', on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.nome)

    class Meta:
        db_table = 'estoque'

gerenciador/models.py
from django.db import models


class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.nome)

    class Meta:
        db_table = 'categoria'

gerenciador/forms.py
from django.forms import ModelForm
from .models import produto, estoque


class ProdutoForm(ModelForm):
    class Meta:
        model = produto
        fields = ('nome', 'data_validade', 'preco', 'quantidade', 'categoria', 'estoque')

    def save(self, commit=True):
        p = super(ProdutoForm, self).save()
        p.estoque= self.cleaned_data['estoque']
        p.categoria = self.cleaned_data['categoria']

        if commit:
            p.save()
        return p


class EstoqueForm(ModelForm):
    class Meta:
        model = estoque
        fields = ['nome']

gerenciador/views.py
from django.views.generic.base import TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from estoques.models import Estoque
from produtos.models import Produto
from vendas.models import Vendas
from django.db.models import Q
from django.db.models import Sum
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from Estoque.utils import render_to_pdf


class GeneratePDFVendas(View):
    def get(self, request, *args, **kwargs):

        vendas = Vendas.objects.order_by('data').filter(usuario=self.request.user)
        data = {'vendas': vendas}

        pdf = render_to_pdf('relatorio.html', data)

        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Relatorio_Vendas.pdf"
            content = 'attachment; filename=%s' % (filename)
            response['Content-Disposition'] = content
            return response
        else:
            return HttpResponse("Not found")


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_queryset(self):
        estoque = Estoque.objects.get(usuario=self.request.user.id)
        return estoque

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        est = Estoque.objects.filter(Q(usuario=self.request.user.id)).count()
        context['list_estoque'] = est

        estok = Estoque.objects.filter(Q(usuario=self.request.user.id))
        prod = Produto.objects.filter(estoque__in=estok).aggregate(qtd=Sum('quantidade'))['qtd']
        context['list_produto'] = prod

        venda = Vendas.objects.filter(Q(usuario=self.request.user.id)).count()
        context['list_venda'] = venda
        return context

        ##Gráficos##

    def home(request):
        return render(request, 'index.html')

    def vendas_chart(request):
        user = request.user.id
        labels = []
        data = []

        queryset = Vendas.objects.filter(usuario=user).values('produto__nome').annotate(Sum('quantidade'))[:10]
        for entry in queryset:
            labels.append(entry['produto__nome'])
            data.append(entry['quantidade__sum'])

        return JsonResponse(data={
            'labels': labels,
            'data': data,
        })

    def estoques_chart(request):
        user = request.user.id
        estoques = Estoque.objects.filter(usuario=user)

        labels1 = []
        data1 = []

        query = Produto.objects.filter(estoque__in=estoques).values('estoque__nome').annotate(Sum('quantidade'))[:10]
        for e in query:
            labels1.append(e['estoque__nome'])
            data1.append(e['quantidade__sum'])

        return JsonResponse(data={
            'labels1': labels1,
            'data1': data1,
        })

gerenciador/templates/cadastroEstoque.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cadastro</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->]

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.name|title }} {{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Cadastrar Estoque</h1>
                        </div>
                        <form method="post" class="user">
                            {% csrf_token %}
                            <div class="form-group row">
                                <div class="col-sm-12 mb-3 mb-sm-0">
                                    <input type="text" class="form-control form-control-user" name="nome"
                                           value="{{ nome }}" placeholder="Nome">
                                </div>
                            </div>
                             <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="hidden" name="id_usuario" id="id_usuario" value="{{ user.id }}">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                            <hr>
                        </form>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

gerenciador/templates/estoqueDelete.html
{% extends 'base.html' %}

{% block title %}
    Meus Estoques
{% endblock title %}

{% block page %}
    <h3 style="margin-top: .8rem;">Deletar Estoque</h3>
{% endblock page %}

{% block content %}
    <!-- Content Row -->
    <div class="row">
        <div class="card" style="margin-top:20px;">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <h2>Você realmente deseja excluir o estoque: "{{ object.nome }}" ?</h2>
                    <input class="btn btn-danger btn-user btn-block" type="submit" value="Confirmar">
                </form>
            </div>
        </div>

    </div>
{% endblock content %}

gerenciador/templates/estoqueList.html
{% extends 'base.html' %}

{% block title %}
    Meus Estoques
{% endblock title %}

{% block page %}
    <h3 style="margin-top: .8rem;">Meus Estoques</h3>
{% endblock page %}

{% block content %}
    <!-- Content Row -->
    <div class="row">
        {% csrf_token %}
        {% for estoque in estoque_list %}
            <div class="card" style="margin-top:20px;">
                <div class="card-header">
                    <h3>{{ estoque.nome }}</h3>
                </div>
                <div class="footer" style="margin: 20px;">

                    <div class="btn-group">
                        <a class="btn btn-primary mr-3" href="{% url 'estoque_update' estoque.id %}">
                            <i class="fas fa-edit"></i>
                            <span>Editar</span>
                        </a>
                    </div>

                    <div class="btn-group">
                        <a class="btn btn-danger mr-3"
                           href="{% url 'estoque_delete' estoque.id %}">
                            <i class="fas fa-trash-alt"></i>
                            <span>Excluir</span>
                        </a>
                    </div>

                     <div class="btn-group">
                        <a class="btn btn-danger mr-3"
                           href="{% url 'estoque_delete' estoque.id %}">
                            <i class="fas fa-trash-alt"></i>
                            <span>Add Produto</span>
                        </a>
                    </div>

                    <div class="btn-group">
                        <a class="btn btn-danger mr-3"
                           href="{% url 'estoque_delete' estoque.id %}">
                            <i class="fas fa-trash-alt"></i>
                            <span>Ver</span>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

gerenciador/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Estoque
{% endblock title %}

{% block page %}
{% endblock page %}

{% block content %}
    <!-- Content Row -->
    <div class="row">
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Estoques Gerenciados
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ list_estoque }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-sort-amount-up fa-2x text-gray-300 "></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Quantidade de Produtos
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ list_produto }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-paste fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Total de Vendas
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ list_venda }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-tasks fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <a class="btn btn-primary mr-3"
               href="{% url 'relatorio' %}">
                <i class="fa fa-download"></i>
                <span>Relatório de Vendas</span>
            </a>
        </div>
    </div>



    <!-- Content Row -->
    <!-- Bar Chart -->
    <div class="row">
        <div class="card shadow mb-4 col-md-6">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Produtos Mais Vendidos</h6>
            </div>
            <div class="card-body">
                <div class="chart-bar">
                    <canvas id="vendas-chart" data-url="{% url 'vendas-chart' %}"></canvas>
                </div>
                <hr>
            </div>
        </div>

        <div class="card shadow mb-4 col-md-6">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Estoques/Quantidade de Produtos</h6>
            </div>
            <div class="card-body">
                <div class="chart-bar">
                    <canvas id="estoques-chart" data-url="{% url 'estoques-chart' %}"></canvas>
                </div>
                <hr>
            </div>
        </div>
    </div>

{% endblock content %}

{% block js %}
    <script>
        $(function () {
            var $vendasChart = $("#vendas-chart");
            $.ajax({
                url: $vendasChart.data("url"),
                success: function (data) {

                    var ctx = $vendasChart[0].getContext("2d");

                    new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: data.labels,
                            datasets: [{
                                label: "Total",
                                backgroundColor: "#4e73df",
                                hoverBackgroundColor: "#2e59d9",
                                borderColor: "#4e73df",
                                data: data.data
                            }]
                        },
                        options: {
                            maintainAspectRatio: false,
                            layout: {
                                padding: {
                                    left: 10,
                                    right: 25,
                                    top: 25,
                                    bottom: 0
                                }
                            },
                            scales: {
                                xAxes: [{
                                    time: {
                                        unit: 'month'
                                    },
                                    gridLines: {
                                        display: false,
                                        drawBorder: false
                                    },
                                    ticks: {
                                        maxTicksLimit: 6
                                    },
                                    maxBarThickness: 25,
                                }],
                                yAxes: [{
                                    ticks: {
                                        min: 0,
                                        max: 100,
                                        maxTicksLimit: 10,
                                        padding: 10,
                                    },
                                    gridLines: {
                                        color: "rgb(234, 236, 244)",
                                        zeroLineColor: "rgb(234, 236, 244)",
                                        drawBorder: false,
                                        borderDash: [2],
                                        zeroLineBorderDash: [2]
                                    }
                                }],
                            },
                            legend: {
                                display: false
                            },
                            tooltips: {
                                titleMarginBottom: 10,
                                titleFontColor: '#6e707e',
                                titleFontSize: 14,
                                backgroundColor: "rgb(255,255,255)",
                                bodyFontColor: "#858796",
                                borderColor: '#dddfeb',
                                borderWidth: 1,
                                xPadding: 15,
                                yPadding: 15,
                                displayColors: false,
                                caretPadding: 10,
                            },
                        }

                    });

                }
            });

        });

        $(function () {
            var $estoquesChart = $("#estoques-chart");
            $.ajax({
                url: $estoquesChart.data("url"),
                success: function (data) {

                    var ctx1 = $estoquesChart[0].getContext("2d");

                    new Chart(ctx1, {
                        type: 'bar',
                        data: {
                            labels: data.labels1,
                            datasets: [{
                                label: "Total",
                                backgroundColor: "#4e73df",
                                hoverBackgroundColor: "#2e59d9",
                                borderColor: "#4e73df",
                                data: data.data1
                            }]
                        },
                        options: {
                            maintainAspectRatio: false,
                            layout: {
                                padding: {
                                    left: 10,
                                    right: 25,
                                    top: 25,
                                    bottom: 0
                                }
                            },
                            scales: {
                                xAxes: [{
                                    time: {
                                        unit: 'month'
                                    },
                                    gridLines: {
                                        display: false,
                                        drawBorder: false
                                    },
                                    ticks: {
                                        maxTicksLimit: 6
                                    },
                                    maxBarThickness: 25,
                                }],
                                yAxes: [{
                                    ticks: {
                                        min: 0,
                                        max: 1000,
                                        maxTicksLimit: 10,
                                        padding: 10,
                                    },
                                    gridLines: {
                                        color: "rgb(234, 236, 244)",
                                        zeroLineColor: "rgb(234, 236, 244)",
                                        drawBorder: false,
                                        borderDash: [2],
                                        zeroLineBorderDash: [2]
                                    }
                                }],
                            },
                            legend: {
                                display: false
                            },
                            tooltips: {
                                titleMarginBottom: 10,
                                titleFontColor: '#6e707e',
                                titleFontSize: 14,
                                backgroundColor: "rgb(255,255,255)",
                                bodyFontColor: "#858796",
                                borderColor: '#dddfeb',
                                borderWidth: 1,
                                xPadding: 15,
                                yPadding: 15,
                                displayColors: false,
                                caretPadding: 10,
                            },
                        }

                    });

                }
            });

        });
    </script>
{% endblock js %}

gerenciador/templates/relatorio.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Relatorio de Vendas</title>
    <style type="text/css">
        body {
            font-weight: 200;
            font-size: 14px;
        }

        .header {
            font-size: 20px;
            font-weight: 100;
            text-align: center;
            color: black;
        }

        .title {
            font-size: 22px;
            font-weight: 100;
            /* text-align: right;*/
            padding: 10px 20px 0px 20px;
        }

        .title span {
            color: black;
        }

        .details {
            padding: 10px 20px 0px 20px;
            text-align: left !important;
            /*margin-left: 40%;*/
        }

        .hrItem {
            border: none;
            height: 1px;
            /* Set the hr color */
            color: #333; /* old IE */
            background-color: #fff; /* Modern Browsers */
        }

        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            text-align: center;
            padding: 5px;
        }
    </style>
</head>
<body>
<div class='wrapper'>
    <div class='header'>
        <p class='title'>Relatorio de Vendas</p>
    </div>
    <!--<hr class='hrItem'/>-->
    <h2 style="text-align: center">Listagem das Vendas</h2>
    <div>
        <div class='details'>
            <table>
                <tr>
                    <th>Número</th>
                    <th>Data</th>
                    <th>Cliente</th>
                    <th>Produto</th>
                    <th>Quantidade</th>
                </tr>
                {% for Venda in vendas %}
                    <tr>
                        <td>{{ Venda.numero }}</td>
                        <td>{{ Venda.data }}</td>
                        <td>{{ Venda.cliente }}</td>
                        <td>{{ Venda.produto.nome }}</td>
                        <td>{{ Venda.quantidade }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
</body>
</html>