Estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title=' API`s Estoque DSC ')

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('gerenciador.urls')),
    path('', include('estoques.urls')),
    path('', include('produtos.urls')),
    path('', include('vendas.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger/', schema_view),

]

produtos/urls.py
from django.urls import path, include
from .views import ProdutoView,ProdutoDeleteView,ProdutoUpdateView,ProdutoListView

from rest_framework import routers
from .api.viewsets import ProdutoViewSet

router = routers.DefaultRouter()
router.register(r'produto', ProdutoViewSet)

urlpatterns = [
    path('api', include(router.urls)),
    path('produto/<int:pk>', ProdutoView.as_view(), name="produto"),
    path('listarProdutos/<int:pk>', ProdutoListView.as_view(), name='produto_list'),
    path('editarProduto/<int:pk>', ProdutoUpdateView.as_view(), name='produto_update'),
    path('deletarProduto/<int:pk>/', ProdutoDeleteView.as_view(), name='produto_delete'),

]

vendas/urls.py
from django.urls import path, include
from .views import VendasView, VendasListView, VendasDeleteView, VendasUpdateView

from rest_framework import routers
from .api.viewsets import VendaViewSet

router = routers.DefaultRouter()
router.register(r'venda', VendaViewSet)

urlpatterns = [
    path('api', include(router.urls)),
    path('venda/<int:pk>', VendasView.as_view(), name="venda"),
    path('listarVenda/', VendasListView.as_view(), name='venda_list'),
    path('editarVenda/<int:pk>', VendasUpdateView.as_view(), name='venda_update'),
    path('deletarVenda/<int:pk>/', VendasDeleteView.as_view(), name='venda_delete'),
]

produtos/models.py
from django.db import models


# Create your models here.

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantidade = models.IntegerField()
    categoria = models.ForeignKey("gerenciador.Categoria", on_delete=models.CASCADE)
    estoque = models.ForeignKey("estoques.Estoque", on_delete=models.CASCADE)


    def __str__(self):
        return '{}'.format(self.id)

    class Meta:
        db_table = 'produto'

produtos/forms.py
from django.forms import ModelForm
from .models import Produto


class ProdutoForm(ModelForm):
    class Meta:
        model = Produto
        fields = ('nome','preco', 'quantidade', 'categoria')

produtos/views.py
from django.contrib import messages
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from .forms import ProdutoForm
from .models import Produto
from gerenciador.models import Categoria
from estoques.models import Estoque
from django.contrib.auth.mixins import LoginRequiredMixin


class ProdutoView(LoginRequiredMixin, CreateView):
    model = Produto
    template_name = 'cadastroProduto.html'
    form_class = ProdutoForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['TipoCategoria'] = Categoria.objects.all()
        return context

    def form_valid(self, form):
        produto = form.save(commit=False)
        id = self.kwargs.get("pk")
        estoque_id = Estoque.objects.get(id=id)
        produto.estoque = estoque_id
        produto.save()
        return super(ProdutoView, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Produto cadastrado com sucesso!')
        id_p = self.kwargs.get("pk")
        estoque_id = list(produto.estoque.id for produto in Produto.objects.filter(id=id_p))
        produto = Produto.objects.filter(id__in=estoque_id)

        for member in produto.iterator():
            id = member.id
        return reverse('produto_list', args=[id_p])



class ProdutoListView(LoginRequiredMixin, ListView):
    model = Produto
    context_object_name = 'produto_list'
    template_name = 'produtoList.html'

    def get_queryset(self):
        id = self.kwargs.get("pk")
        estoque_id = list(estoque.id for estoque in Estoque.objects.filter(id=id))
        produto = Produto.objects.filter(estoque__in=estoque_id)
        return produto


class ProdutoUpdateView(LoginRequiredMixin, UpdateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'produtoUpdate.html'

    def get_success_url(self):
        id_p = self.kwargs.get("pk")
        estoque_id = list(produto.estoque.id for produto in Produto.objects.filter(id=id_p))
        produto = Produto.objects.filter(id__in=estoque_id)

        for member in produto.iterator():
            id = member.id
        return reverse('produto_list', args=[id])


class ProdutoDeleteView(LoginRequiredMixin, DeleteView):
    model = Produto
    template_name = 'produtoDelete.html'

    def get_success_url(self):
        id_p = self.kwargs.get("pk")
        estoque_id = list(produto.estoque.id for produto in Produto.objects.filter(id=id_p))
        produto = Produto.objects.filter(id__in=estoque_id)

        for member in produto.iterator():
            id = member.id
        return reverse('produto_list', args=[id])

produtos/templates/cadastroProduto.html
{% extends 'base.html' %}

{% block title %}
    Cadastrar Produto
{% endblock title %}

{% block page %}
    <h3>Cadastrar</h3>
    <a class="btn btn-primary"
       onclick="javascript:history.back();">
        <i class="fas fa-arrow-left"></i>
        <span>Voltar</span>
    </a>
{% endblock page %}

{% block content %}
    <hr>
    <!-- Content Row -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 text-center">
            <h4 class="m-0 font-weight-bold text-primary">Novo Produto</h4>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="p-5">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ field.name|title }} {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post" class="user">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="text" class="form-control form-control-user" name="nome"
                                       required
                                       value="{{ nome }}" placeholder="Nome">
                            </div>
                            <div class="col-sm-6">
                                <input type="number" step="0.01" id="id_preco" class="form-control form-control-user"
                                       name="preco" required
                                       value="{{ preco }}" placeholder="Preço">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="number" id="id_qtd" class="form-control form-control-user"
                                       name="quantidade"
                                       required
                                       value="{{ quantidade }}" placeholder="Quantidade">
                            </div>
                            <div class="col-sm-6">
                                <select class="form-control" id="id_categoria" name="categoria"
                                        required>
                                    <option value="" selected="" disabled>Selecione</option>
                                    {% for categoria in TipoCategoria %}
                                        <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

produtos/templates/produtoDelete.html
{% extends 'base.html' %}

{% block title %}
    Deletar Produto
{% endblock title %}

{% block page %}
    <h3>Deletar</h3>
    <a class="btn btn-primary"
       onclick="javascript:history.back();">
        <i class="fas fa-arrow-left"></i>
        <span>Voltar</span>
    </a>
{% endblock page %}

{% block content %}
    <hr>
    <!-- Content Row -->
    <div class="row justify-content-center m-5">
        <div class="col-12 col-sm-6 col-md-8 d-flex align-items-sm-center flex-column">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <form method="post" class="user">
                            {% csrf_token %}
                            <h4>Você realmente deseja excluir o produto: "{{ object.nome }}" ?</h4>
                            <div class="d-flex align-items-center justify-content-center">
                                <input class="btn btn-danger" type="submit" value="Confirmar">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

produtos/templates/produtoList.html
{% extends 'base.html' %}

{% block title %}
    Produtos
{% endblock title %}

{% block page %}
    <h3>Estoque de Produtos</h3>
    <a class="btn btn-primary"
       onclick="javascript:history.back();">
        <i class="fas fa-arrow-left"></i>
        <span>Voltar</span>
    </a>
{% endblock page %}

{% block content %}
    <hr>
    <!-- Content Row -->
    {% csrf_token %}
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h4 class="m-0 font-weight-bold text-primary ">Produtos</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>Preço</th>
                            <th>Quantidade</th>
                            <th>Categoria</th>
                            <th class="actions">Ações</th>
                        </tr>
                        </thead>
                        {% for Produto in produto_list %}
                            <tbody>
                            <tr>
                                <td>{{ Produto.id }}</td>
                                <td>{{ Produto.nome }}</td>
                                <td>{{ Produto.preco }}</td>
                                <td>{{ Produto.quantidade }}</td>
                                <td>{{ Produto.categoria.nome }}</td>
                                <td class="actions">
                                    <a class="btn btn-primary mr-2" href="{% url 'produto_update' Produto.id %}">
                                        <i class="fas fa-edit"> Editar</i>
                                    </a>
                                    <a class="btn btn-danger mr-2"
                                       href="{% url 'produto_delete' Produto.id %}">
                                        <i class="fas fa-trash-alt"> Excluir</i>
                                    </a>
                                    <a class="btn btn-info mr-2"
                                       href="{% url 'venda' Produto.id %}">
                                        <i class="fas fa-cart-arrow-down"> Venda</i>
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

produtos/templates/produtoUpdate.html
{% extends 'base.html' %}

{% block title %}
    Editar Produto
{% endblock title %}

{% block page %}
    <h3>Editar</h3>
    <a class="btn btn-primary"
       onclick="javascript:history.back();">
        <i class="fas fa-arrow-left"></i>
        <span>Voltar</span>
    </a>
{% endblock page %}

{% block content %}
    <hr>
    <!-- Content Row -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 text-center">
            <h4 class="m-0 font-weight-bold text-primary">Editar Produto</h4>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="p-5">
                {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ field.name|title }} {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post" class="user">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <label>Nome</label>
                                <input type="text" class="form-control form-control-user" name="nome"
                                       required
                                       value="{{ form.nome.value }}">
                            </div>
                            <div class="col-sm-6">
                                <label>Preço</label>
                                 {{ form.preco }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <label>Quantidade</label>
                                <input type="number" id="id_qtd" class="form-control form-control-user"
                                       name="quantidade"
                                       required
                                       value="{{ form.quantidade.value }}">
                            </div>
                            <div class="col-sm-6">
                                <label>Categoria</label>
                                <select id="id_categoria" name="categoria" class="form-control">
                                    {% for cat in form.categoria %}
                                        <tr>
                                            <td>
                                                {{ cat }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Editar</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#id_preco").addClass("form-control form-control-user");
        });
    </script>
{% endblock js %}