Estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title=' API`s Estoque DSC ')

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('gerenciador.urls')),
    path('', include('estoques.urls')),
    path('', include('produtos.urls')),
    path('', include('vendas.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger/', schema_view),

]

estoques/urls.py
from django.urls import path, include
from .views import EstoqueView, EstoqueDeleteView, EstoqueListView, EstoqueUpdateView
from rest_framework import routers
from .api.viewsets import EstoqueViewSet

router = routers.DefaultRouter()
router.register(r'estoque', EstoqueViewSet)

urlpatterns = [
    path('api', include(router.urls)),
    path('estoque/', EstoqueView.as_view(), name='estoque'),
    path('listar/', EstoqueListView.as_view(), name='estoqueList'),
    path('editar/<int:pk>', EstoqueUpdateView.as_view(), name='estoque_update'),
    path('deletar/<int:pk>/', EstoqueDeleteView.as_view(), name='estoque_delete'),
]

vendas/urls.py
from django.urls import path, include
from .views import VendasView, VendasListView, VendasDeleteView, VendasUpdateView

from rest_framework import routers
from .api.viewsets import VendaViewSet

router = routers.DefaultRouter()
router.register(r'venda', VendaViewSet)

urlpatterns = [
    path('api', include(router.urls)),
    path('venda/<int:pk>', VendasView.as_view(), name="venda"),
    path('listarVenda/', VendasListView.as_view(), name='venda_list'),
    path('editarVenda/<int:pk>', VendasUpdateView.as_view(), name='venda_update'),
    path('deletarVenda/<int:pk>/', VendasDeleteView.as_view(), name='venda_delete'),
]

estoques/models.py
from django.db import models

class Estoque(models.Model):
    nome = models.CharField(max_length=100)
    usuario = models.ForeignKey("accounts.CustomUsuario", db_column='id_usuario', on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.nome)

    class Meta:
        db_table = 'estoque'

produtos/models.py
from django.db import models


# Create your models here.

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantidade = models.IntegerField()
    categoria = models.ForeignKey("gerenciador.Categoria", on_delete=models.CASCADE)
    estoque = models.ForeignKey("estoques.Estoque", on_delete=models.CASCADE)


    def __str__(self):
        return '{}'.format(self.id)

    class Meta:
        db_table = 'produto'

estoques/forms.py
from django.forms import ModelForm
from .models import Estoque

class EstoqueForm(ModelForm):
    class Meta:
        model = Estoque
        fields = ['nome']

estoques/views.py
from django.contrib import messages
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from .forms import EstoqueForm
from .models import Estoque
from django.contrib.auth.mixins import LoginRequiredMixin

class EstoqueView(LoginRequiredMixin,CreateView):
    model = Estoque
    success_url = 'estoqueList'
    template_name = 'cadastroEstoque.html'
    form_class = EstoqueForm

    def form_valid(self, form):
        Estoque = form.save(commit=False)
        Estoque.usuario = self.request.user

        Estoque.save()
        return super(EstoqueView, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Estoque cadastrado com sucesso!')
        return reverse(self.success_url)


class EstoqueListView(LoginRequiredMixin,ListView):
    model = Estoque
    context_object_name = 'estoque_list'
    template_name = 'estoqueList.html'

    def get_queryset(self):
        estoques = Estoque.objects.order_by('nome').filter(usuario=self.request.user)
        return estoques


class EstoqueUpdateView(LoginRequiredMixin,UpdateView):
    model = Estoque
    form_class = EstoqueForm
    template_name = 'estoqueUpdate.html'

    def get_success_url(self):
        return reverse('estoqueList')


class EstoqueDeleteView(LoginRequiredMixin,DeleteView):
    model = Estoque
    template_name = 'estoqueDelete.html'

    def get_success_url(self):
        return reverse('estoqueList')

estoques/templates/cadastroEstoque.html
{% extends 'base.html' %}

{% block title %}
    Cadastrar Estoque
{% endblock title %}

{% block page %}
    <h3>Cadastro</h3>
    <a class="btn btn-primary m-3"
       href="{% url 'estoqueList' %}">
        <i class="fas fa-list"></i>
        <span>Meus Estoques</span>
    </a>
{% endblock page %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3 text-center">
            <h4 class="m-0 font-weight-bold text-primary">Novo Estoque</h4>
        </div>
        <!-- Content Row -->
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <form method="post" class="user">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-12 mb-3 mb-sm-0">
                                <input type="text" class="form-control form-control-user" name="nome"
                                       value="{{ nome }}" placeholder="Nome">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

estoques/templates/estoqueDelete.html
{% extends 'base.html' %}

{% block title %}
    Meus Estoques
{% endblock title %}

{% block page %}
    <h3>Deletar Estoque</h3>
    <a class="btn btn-primary"
       onclick="javascript:history.back();">
        <i class="fas fa-arrow-left"></i>
        <span>Voltar</span>
    </a>
{% endblock page %}

{% block content %}
    <hr>
    <!-- Content Row -->
     <!-- Content Row -->
    <div class="row justify-content-center m-5">
        <div class="col-12 col-sm-6 col-md-8 d-flex align-items-sm-center flex-column">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <form method="post" class="user">
                            {% csrf_token %}
                            <h4>Você realmente deseja excluir o estoque: "{{ object.nome }}" ?</h4>
                            <div class="d-flex align-items-center justify-content-center">
                                <input class="btn btn-danger" type="submit" value="Confirmar">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </div>
{% endblock content %}

estoques/templates/estoqueList.html
{% extends 'base.html' %}

{% block title %}
    Meus Estoques
{% endblock title %}

{% block page %}
    <h4>Meus Estoques</h4>
    <a class="btn btn-success"
       href="{% url 'estoque' %}">
        <i class="fas fa-plus"></i>
        <span>Novo</span>
    </a>
{% endblock page %}

{% block content %}
    <hr>
    <!-- Content Row -->
    <div class="container-fluid">
        <div class="row">
            {% csrf_token %}
            {% for Estoque in estoque_list %}
                <div class="col-12 col-lg-6 col-md-6 d-flex align-items-sm-stretch flex-column">
                    <div class="card d-flex flex-fill mb-5">
                        <div class="card-header" style="background-color: #147e84; color: #fff;height: 49px;">
                            <h4>{{ Estoque.nome }}</h4>
                        </div>
                        <div class="footer" style="margin: 30px; height: 30px;">
                            <div class="btn-group">
                                <a class="btn btn-primary ml-3" href="{% url 'estoque_update' Estoque.id %}">
                                    <i class="fas fa-edit"></i>
                                    <span>Editar</span>
                                </a>
                            </div>

                            <div class="btn-group">
                                <a class="btn btn-danger"
                                   href="{% url 'estoque_delete' Estoque.id %}">
                                    <i class="fas fa-trash-alt"></i>
                                    <span>Excluir</span>
                                </a>
                            </div>

                            <div class="btn-group">
                                <a class="btn btn-success"
                                   href="{% url 'produto' Estoque.id %}">
                                    <i class="fas fa-plus"></i>
                                    <span>Produto</span>
                                </a>
                            </div>

                            <div class="btn-group">
                                <a class="btn btn-info"
                                   href="{% url 'produto_list' Estoque.id %}">
                                    <i class="fas fa-search"></i>
                                    <span>Produtos</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
    </div>
{% endblock content %}

estoques/templates/estoqueUpdate.html
{% extends 'base.html' %}

{% block title %}
    Editar Estoque
{% endblock title %}

{% block page %}
    <h3>Editar</h3>
    <a class="btn btn-primary"
       onclick="javascript:history.back();">
        <i class="fas fa-arrow-left"></i>
        <span>Voltar</span>
    </a>
{% endblock page %}

{% block content %}
    <hr>
    <div class="card shadow mb-4">
        <div class="card-header py-3 text-center">
            <h4 class="m-0 font-weight-bold text-primary">Editar Estoque</h4>
        </div>
        <!-- Content Row -->
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <form method="post" class="user">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-12 mb-3 mb-sm-0">
                                <input type="text" class="form-control form-control-user" name="nome"
                                       value="{{ form.nome.value }}" placeholder="Nome">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Editar</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}